# Azure Web App Deployment Workflow

name: Build and deploy Node.js app to Azure Web App - user-azra-mern-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      # Install backend dependencies
      - name: Install server dependencies
        run: npm install

      # Install frontend dependencies
      - name: Install client dependencies
        run: |
          cd client
          npm install

      # Build React frontend
      - name: Build React app
        run: |
          cd client
          npm run build

      # Upload everything for deployment
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_92883286AF0143BBB733E6646C63B236 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_DBE8D4B313D54F8B9F5C615608E921EF }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F2DB1731E3E44231957465CBCB905281 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "user-azra-mern-app"
          slot-name: "Production"
          package: .
